export interface Settings {
    allow_personalized_ads: boolean,
    allow_cookies: boolean,
    allow_selling_your_information: boolean,
    allow_location_history: boolean,
    autoplay: boolean,
    country: string,
    display_sensitive_media: boolean,
    dm_allowed_from: 'all' | 'verified' | 'following',
    dm_groups_allowed_from: 'all' | 'following',
    dm_receipts: boolean,
    dm_quality_filter: boolean,
    eu: boolean,
    is_email_public: boolean,
    is_phone_number_public: boolean,
    lang: string,
    nsfw: boolean,
    personalized_trends: boolean,
    protected: boolean,
    show_current_audiospace_publicly: boolean,
    username: string
}
